# Generated by Django 3.0.8 on 2020-07-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='catagory',
            new_name='author',
        ),
    ]
