# Generated by Django 3.0.8 on 2020-07-19 19:29

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200719_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=dashboard.models.update_filename),
        ),
    ]
