# Generated by Django 3.0.8 on 2020-07-24 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0009_books_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='user_id',
            field=models.ManyToManyField(related_name='ubooks', to=settings.AUTH_USER_MODEL),
        ),
    ]
